# dockerfile.yml
version: '3'

services:
  app:
    image: node:20
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "21041:21041"
    volumes:
      - .:/app
    command: npm start

